export const CHANGE_SEARCH_VALUE = 'CHANGE_SEARCH_VALUE';
export const REQUEST_ITEMS_PENDING = 'REQUEST_ITEMS_PENDING';
export const REQUEST_ITEMS_SUCCESS = 'REQUEST_ITEMS_SUCCESS';
export const REQUEST_ITEMS_FAILED = 'REQUEST_ITEMS_FAILED';
export const CREATE_ALERTS = "CREATE_ALERTS";
export const CLEAR_ALERTS = "CLEAR_ALERTS";
